### ISSUE TITLE
Application crashes as soon as server is started

### ISSUE THREAD

**Issue by zenseii** [FIX94/WiiUGamepadToMouse#1]
Thank you so much for this application. I was looking for something just like this.

I am trying to run the application in Win10 64-bit with usendmii client version 0.2.0 and 0.1.0 and it crashes everytime I start the server while the client Wii U is connected to the server. As long as the Wii U is not connected/trying to connect to the server's IP, however, the application does not crash, even if the server is started. I have tried both releases of this application.

I have made sure that the application is allowed through Windows' firewall. 

Using usendmiiclient with usendmii works without any problems.

Both server and client are connected to the router wirelessly, and I have tried to have the client connected via cable without any difference.

**Comment by FIX94** [comment]
how strange, 64bit windows 10 here too and I never once have seen a crash so I am a little confused as to how it would even crash to be honest, do you just have the gamepad connected without any like wiimotes or something of the sort? Also, is there any type of crashlog or something you can maybe provide? cause I have no idea what could be going on at all with that little information.

**Comment by zenseii** [comment]
Yes, I'm sorry but I've tried to give as much information as possible. Still, there are no other controllers connected. The program closes itself without any fanfare. So there is no crash as in the program freezing or stopping to respond. It just closes. I do not know where I could get any kind of log of what happens. I have tried to look in Windows Event Viewer without much luck really.

**Comment by zenseii** [comment]
So I've opened the git source in visual studio and started debugging. As soon as I start the server when the client is waiting to connect I get this exception:
```
System.FormatException
  HResult=0x80131537
  Message=Input string was not in a correct format.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```
The output window gives me this info:
`Exception thrown: 'System.FormatException' in mscorlib.dll
An unhandled exception of type 'System.FormatException' occurred in mscorlib.dll
Input string was not in a correct format.`

The exception points me to this line of code:
`Double lStickY = Double.Parse(wiiUGamePad.Element("lStickY").Value);`


If I try to run the server without the Wii U trying to connect then it does not crash, but the debug output keeps repeating this message:

`Exception thrown: 'System.Net.Sockets.SocketException' in System.dll`

I hope this is a bit more helpful and I'm sorry for not being of more help, but it is the first time I ever try to do this.

**Comment by FIX94** [comment]
thank you so much for already going this far, it helps out a lot! So what I assume is happening is that somehow your analog sticks are not properly being read on the wiiu client side, so when it tries to parse it back in the server it just crashes because the value is invalid. Try replace the code with this, it should now handle that exception and just continue, and also on the output window print out the data the wiiu sends back for each received thing, if you could copy paste me that output, that'd be great so we can see exactly what the analog sticks do for you. Also when testing just try move the analog sticks so we can see if they even update at all in that data.
[Form1.zip](https://github.com/FIX94/WiiUGamepadToMouse/files/4140358/Form1.zip)

**Comment by zenseii** [comment]
Yes, now all inputs work and are registered as expected, except for moving either analog sticks! Here's the debug output without any inputs given:
[Output-Debug.txt](https://github.com/FIX94/WiiUGamepadToMouse/files/4140882/Output-Debug.txt)

The exception error happens pretty frequently as you can see. Also, the gyro keeps sending inputs even though I don't think your app uses the gyro for anything?

I saw that the left stick and right stick do register as values:
Left stick holding left `"hold":1073741824 "lStickX":-0.9901186824,"lStickY":0.1402314007,`
Left stick holding up `"hold":268435456 "lStickX":0.08417326212,"lStickY":0.9964510798,`
Left stick holding down `"hold":134217728, "lStickX":-0.2210059464, "lStickY":-0.9752724767`
Left stick holding right `"hold":536870912, "lStickX":0.9999806881,"lStickY":0.00622210186,`

Right stick holding left `"hold":67108864, "rStickX":-0.9993478656,"rStickY":0.03611012921,`
Right stick holding up `"hold":16777216 "rStickX":0.05497745797,"rStickY":0.9984876513`
Right stick holding down `"hold":8388608 "rStickX":-0.1060763523,"rStickY":-0.9943580031`
Right stick holding right `"hold":33554432 "rStickX":0.9782448411,"rStickY":-0.2074538618`

I realise I could try a complete spin of the analog sticks to get the full area of it but the debug output would quickly become over 1000 pages.

**Comment by FIX94** [comment]
Thanks, that also helped a bunch, I think I understand the issue now, so the code I added below should now function properly including the analog stick scrolling, if you can confirm that I'll release it as 0.3. Also, the data it printed out is just what the client sends over in raw form so I could make sure the data was sane that was being sent over and it was, it actually was an issue because double values in your current set country are written with a comma like 0,5 instead of a dot 0.3 so that code below should make it always intepret it with the dot as the wiiu sends it.
[Form1.zip](https://github.com/FIX94/WiiUGamepadToMouse/files/4141304/Form1.zip)

**Comment by zenseii** [comment]
Great! I just tested it and it all works now. Both pair of shoulder buttons work as left and right click. Both sticks scroll in y direction. A and B work as left and right click too. Clicking both l and r sticks work as mouse wheel middle click as well. It's ironic how this problem essentially comes from the world not being able to agree on something as trivial as comma and period..

Out of curiosity, I was wondering why the program sometimes gives this exception either when it is waiting for the client to connect or when the client is connected and idle?:

`Exception thrown: 'System.Net.Sockets.SocketException' in System.dll`

Is it because of loss of signal/bad connection?

Anyways, thanks again for helping out with this! Now I can finally try this out with some strategy games and point n click games with my pc connected to the tv 👌 I have been trying to use my phone as a sort of replacement for a mouse but it is not precise enough.

**Comment by FIX94** [comment]
That exception is normal and is handled automatically, it retries right away when no connection was established. Anyways, I made a new release now, v0.3, so try that official zip and we should be all good now :)

**Comment by zenseii** [comment]
Just tested out version 0.3 and it works great! This issue can now be closed.
